### ISSUE TITLE
RAG index incorrectly used in API to filter files

### ISSUE THREAD

**Issue by ChrisGarrattCGI** [athrael-soju/Titanium#92]
RAG API Operations `delete-file` and `update-file-status` are both using the `ragId` field in `fileCollection.deleteOne()` and `fileCollection.updateOne()` respectively. The RAG index is defined on the user and allocated to every rag file that user then uploads  meaning it is not unique to each file separately and causes inconsistencies in these operations that are trying to operate on specific files.

**Comment by athrael-soju** [comment]
Completed by https://github.com/athrael-soju/Titanium/pull/93
